### ISSUE TITLE
Log rotation divolte-collector.log

### ISSUE THREAD

**Issue by BHMath** [divolte/divolte-collector#108]
Hi,

My divolte instance is running for like 6 month now, with some restart but my log file is growing indefinitely. Currently my file is 3GB.

Can you add a way to rotate log everyday and only keep like 7 days log files ?

**Comment by krisgeus** [comment]
https://github.com/divolte/divolte-collector/blob/master/rpm/SOURCES/divolte-collector.logback.xml

Is configured to do the rolling file magic.
Not sure if you use the rpm based install though.

If not you can put this file on your filesystem and use the following extra option to the starting of divolte-collector to use it:
-Dlogback.configurationFile=/etc/divolte/logback.xml

Let me know if this helps you

**Comment by BHMath** [comment]
No I didn't use rpm, just the tar.

I will test that thanks.

**Comment by BHMath** [comment]
Thanks it seems to be working well now. Sorry for the delay.
