### ISSUE TITLE
Configuration Examples for javascript are divolte.tracking.javascript instead of divolte.javascript

### ISSUE THREAD

**Issue by phperet** [divolte/divolte-collector#116]
For the divolte.javascript part of the configuration doc, all the examples are divolte.tracking.javascript instead of divolte.javascript.
Tooks me some days to figure out why my config didn't worked after copy/paste of the doc :yum:

**Comment by friso** [comment]
Thanks for noticing @phperet and apologies for making things harder than they should be. This issue has been noted before and is fixed on master. Unfortunately, it didn't make it to a release just yet.

We hope to have a 0.4 release soon-ish, which includes a major overhaul of how the configuration works. Once we merge all that, the docs will reflect reality again.
