### ISSUE TITLE
Divolte collector Custom js events tracking

### ISSUE THREAD

**Issue by BirgulAyaz** [divolte/divolte-collector#169]
How can i follow new custom js event with divolte collector. ?

i want to tracking lazy load event with divolte collector. how many image is load by visitor on the browser ?

**Comment by friso** [comment]
Mapping custom even parameters is described [http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.5.0/userdoc/html/mapping_reference.html#complex-value-eventparameters](here).

For these kinds of enquiries you can best use the [https://groups.google.com/forum/#!forum/divolte-collector](mailing list) on Google Groups, though.

Closing this issue.
