### ISSUE TITLE
cross domain data sharing

### ISSUE THREAD

**Issue by iqbalhasnan** [divolte/divolte-collector#170]
Hello, I was wondering whether divolte collector support cross domain data sharing ?

Is it possible to have the same partyId when I first visit Site-A.com then Site-B.com

**Comment by friso** [comment]
Perhaps questions are better suited for the [mailing list](https://groups.google.com/forum/#!forum/divolte-collector).

That said, basically there is nothing in Divolte that either prevents or enables you to do cross domain tracking. When left unconfigered, Divolte uses the requested host to set the cookie domain used for the identification cookies. You can also configure it to a domain of your choosing. The issues with cross domain tracking is that most browsers prevent you from sending cookies across domains.

**Comment by iqbalhasnan** [comment]
thanks @friso
