### ISSUE TITLE
Could not find io.divolte:divolte-schema:0.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by ppcuban** [divolte/divolte-collector#178]
I cloned your repo and followed your instruction (README). When I run...

`./gradlew zip` (also tarball and test) 

I am getting the following error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find io.divolte:divolte-schema:0.7.0-SNAPSHOT.
  Searched in the following locations:
      file:/Users/xxxxx/.m2/repository/io/divolte/divolte-schema/0.7.0-SNAPSHOT/maven-metadata.xml
      file:/Users/xxxxx/.m2/repository/io/divolte/divolte-schema/0.7.0-SNAPSHOT/divolte-schema-0.7.0-SNAPSHOT.pom
      file:/Users/xxxxx/.m2/repository/io/divolte/divolte-schema/0.7.0-SNAPSHOT/divolte-schema-0.7.0-SNAPSHOT.jar
      https://repo1.maven.org/maven2/io/divolte/divolte-schema/0.7.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/divolte/divolte-schema/0.7.0-SNAPSHOT/divolte-schema-0.7.0-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/divolte/divolte-schema/0.7.0-SNAPSHOT/divolte-schema-0.7.0-SNAPSHOT.jar
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```
When I manually try to reach _https://repo1.maven.org/maven2/io/divolte/divolte-schema/0.7.0-SNAPSHOT/maven-metadata.xml_ I get a 404. 

Thanks.

**Comment by friso** [comment]
The default Avro schema for Divolte is in a separate project. The master branch of Divolte depends on a snapshot version of this project. Snapshot versions are not deployed to Maven Central, so you have to install it locally.

If you clone the [divolte-schema](https://github.com/divolte/divolte-schema) repo and run a `mvn install` from that project's root dir, it will install the correct dependency locally. Afterwards you should be able to build Divolte as per the instructions.

We should probably add this to the README though.
