### ISSUE TITLE
Do we have plan to make divolte-collector support Confluent Schema Registry for Avro Kafka message?

### ISSUE THREAD

**Issue by ChenShuai1981** [divolte/divolte-collector#184]
Do we have plan to make divolte-collector support Confluent Schema Registry for Avro Kafka message?

**Comment by asnare** [comment]
Support for Confluent-compatible Avro Kafka messages has been merged to master (#146) and will be part of 0.7 when the release is tagged. However the registry itself is not directly supported.

Support for the directly contacting the registry was discussed as part of issue #135: the short summary is that registering the schema can be done as part of deployment and its id then configured in the Kafka sink.
