### ISSUE TITLE
Improve shutdown/load-balancer integration

### ISSUE THREAD

**Issue by asnare** [divolte/divolte-collector#193]
At present, when a SIGTERM is received the following happens:

1. The HTTP stops processing new requests. (Any new requests get a `503` response.)
2. Existing HTTP requests that are underway are allowed to complete.
3. Once in-flight requests have completed, the HTTP server stops accepting new connections entirely.
4. Events in the mapping/sink pipeline are flushed.
5. The whole server stops.

This causes problems with some load-balancers, who continue to forward traffic to a node until the health check takes the node out of rotation. In addition, load-balancers don't always retry failed requests. This means that requests between the initial SIGTERM and the health check marking the node as unhealthy will fail: the request can be forwarded to a node that has shut itself down, yielding an error that will be propagated to the client.

In order to help with deployment in these situations, we plan to introduce a new feature allowing for delayed shutdown. This will consist of:

 - A new configuration item: `global.server.delay_shutdown` that defaults to 0 ms.
 - On SIGTERM:
    1. Mark the `/ping` handler to start returning a 503 status code, and the body should change to something else that _doesn't_ contain `pong`. (I kind of like `no p*ng for you: ${DELAY_TIMEOUT}`.)
    2. Start a timer for the `global.server.delay_shutdown` duration.
 - When the timer lapses, start the current shutdown process.

This allows users to configure the delay interval such that requests continue to be served until their health check mechanism stops forwarding requests to the node.

**Comment by asnare** [comment]
Kubernetes is one of the things we're aiming to help with. In particular when stopping a pod it continues to deliver traffic to it between the SIGTERM and the next readiness probe. During this interval we respond with 503 (or don't accept the connection) and that hits the client.

The situation with HAProxy is the similar out-of-the-box: there's an option to have it retry requests that fail but it's not on by default.

The goal here is to help with any load-balancer that supports a readiness check, even if they don't have any extra knowledge about node availability.

Getting back to Kubernetes' liveness and readiness checks, I think as things currently stand the `/ping` endpoint is suitable for a readiness check and would remain so under this proposal but behave better. For liveness any of the javascript endpoints are better, and are unaffected by this proposal.

Have I missed something?

**Comment by friso** [comment]
Would it then make sense to initiate the shutdown sequence only after the first invocation of readiness after SIGTERM has been responded with a 503.

**Comment by asnare** [comment]
That would work for Kubernetes, OpenShift and ELB (I think), although not out of the box: they default to 3 failing probes before marking it unhealthy.

It would work for HAProxy if there's a single server and it's configured to mark it as unhealthy after a single failing probe. In a HA setup each server does its own health check, so it wouldn't work there. It's also normal to have a few failing probes before you mark a node unhealthy.

We could make the thing ultra-configurable, but it seems rather brittle when all cases can be covered with a single "fail `/ping` for _x_ seconds before really shutting down" setting.

_…time passes…_

I've been doing some reading, and I'm also not 100%-convinced that the interwebs understand the problem correctly with Kubernetes. Specifically, [its documentation states](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) that when terminating a pod the following happen in parallel:

 - Processes get a `TERM` signal.
 -
      > Pod is removed from endpoints list for service, and are no longer considered part of the set of running pods for replication controllers. Pods that shutdown slowly can continue to serve traffic as load balancers (like the service proxy) remove them from their rotations.

I would assume this is racy, and there's at least [one report](https://stackoverflow.com/a/40842584) that agrees. In particular I don't think the readiness probe is relevant here, except in the sense that it could _also_ cause a pod to be marked as unavailable.

With this in mind I _think_ the original proposal still stands. Right now though I'm going to sleep on it…

**Comment by Fokko** [comment]
I took this as a reference: https://github.com/RisingStack/kubernetes-graceful-shutdown-example

The idea is to verify the graceful shutdown by performing a test. By firing a predefined set amount of requests and check if they all arrive properly. I'll let you guys know what the impact of the change will be.

**Comment by asnare** [comment]
@Fokko So I'm wondering if that reference describes Kubernetes as it actually works. Specifically, its description contradicts the Kubernetes documentation.

**Comment by Fokko** [comment]
Good point, right now we're still on Kubernetes 1.7, so it might even change in 1.8 or 1.9
