### ISSUE TITLE
Is Divolte compatible with Java 11?

### ISSUE THREAD

**Issue by shermank1** [divolte/divolte-collector#242]
Is Divolte compatible with Java 11? If so, I'm having issues with the JAVA_HOME setup. Please assist? The guide is great, but passes over what seem to be fundamental setup issues. Looking forward to a response, thanks in advance.

**Comment by asnare** [comment]
We've tested Divolte against Java 11 and didn't notice anything in particular. Could you be a bit more specific about the problems you're having with `JAVA_HOME`?

**Comment by shermank1** [comment]
Good day Andrew,

I get an error message saying: 'JAVA_HOME not set, java not found' - yet
I've installed Java and have checked the installation using 'java -version'.

I've tried a few solutions, using the JAVA_HOME = command, and editing the
bash terminal - yet still get the same error.

I'm really amazed with what I understand Divolte can do, and seriously want
to experience it myself.

Any assistance with getting Divolte running will help tremendously.

Kind regards/Sherman

**Comment by asnare** [comment]
Which platform are you using?  
How are you trying to run Divolte?

If you're trying to do it by hand, `JAVA_HOME` needs to be set in the environment when you run the command that starts it. That normally means `export JAVA_HOME='…'` on Linux/macOS, for example.

**Comment by shermank1** [comment]
I'm using Ubuntu 18. I've tried the export command too - no use.

If I'm not doing it by hand, whats the easiest, least complicated way to do
it?

**Comment by shermank1** [comment]
Hi Andrew,

Trust you are well. I've managed to get divolte-collector working, after
following your advice - I had the path set incorrectly.

I'm now receiving an error message :'WARNING: An illegal reflective access
operation has occurred'.[Please see attached screenshot].

[image: Screenshot from 2019-05-04 11-47-51.png]

Is this a common issue or some error on my part?

Regards,
Sherman.

**Comment by asnare** [comment]
This is an unfortunate, but expected, warning triggered by some of the components that we use. Until these components are updated warnings like these are to be expected under Java 11 and Java 12.

**Comment by shermank1** [comment]
Thanks Andrew - will update - I got the collector to work, in spite of the
error messages - I'm setting up and configuring Hadoop - so far, so good.
Much Appreciated.
