### ISSUE TITLE
Support for mapping to complex Avro schema

### ISSUE THREAD

**Issue by DaveSlinn** [divolte/divolte-collector#267]
Is an Avro schema like this, which includes a custom complex type called ExtraData in the schema def, allowed?
```
[
    {
        "namespace": "com.example",
        "type": "record",
        "name": "ClickstreamEvent",
        "fields": [
            { "name": "topicName",            "type": "string"},
            { "name": "timestamp",            "type": "long"},
            { "name": "data",                 "type": "ExtraData"}
         ]
    },
    {
        "namespace": "com.example",
        "type": "record",
        "name": "ExtraData",
        "fields": [
            { "name": "id",          "type": "string"},
            { "name": "source",      "type": "string"},
            { "name": "name",        "type": "string"}
       ]
    }
]
```
And the desired resulting event in Kafka would look like this:
```
{
  "topicName": "something",
  "timeStamp": 1562363361995,
  "data": {
    "id": "12345",
    "source": "something else",
    "name": "joe"
  }
}
```
Possible?  The docs don't seem to mention how to create the mapping.groovy file for something like this, and I'm not too familiar with groovy to figure it out on my own.

**Comment by friso** [comment]
Yes, you can map your custom event parameters onto a complex field of your Avro schema.

See [here](http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/userdoc/html/mapping_reference.html#mapping-json-jsonnode-to-avro-fields) and [here](http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/userdoc/html/mapping_reference.html#complex-value-eventparameters). Also, you can perform extractions from your event parameters using [JSON Path](http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/userdoc/html/mapping_reference.html#derived-complex-value-eventparameters-path-expression).

**Comment by DaveSlinn** [comment]
I don't think that's not quite what I was looking for. I was wondering if it's possible to have a separate map statement in the groovy file for each individual subitem value? Something like this:
```
mapping {
  map 'something' onto 'topicName'
  map timestamp() onto 'timestamp'
  map eventParameters().value('id') onto 'data.id'
  map eventParameters().value('source') onto 'data.source'
  map eventType() onto 'data.name'
}
```

**Comment by friso** [comment]
Ah, got it. No constructing an object field by field can only be done at the root level right now. The only option is if you manage to get the right result from a JSONPath expression and map it all at once.

**Comment by DaveSlinn** [comment]
Understood. Thanks for the help.
