### ISSUE TITLE
divolte.js blocked

### ISSUE THREAD

**Issue by MrMoronIV** [divolte/divolte-collector#319]
In Opera, when the built-in adblocker is enabled is block the loading of divolte.js. Is there a way around this, by for example changing the divolte.js filename or do we have to live with it?

How can we change the divolte.js filename that we need to include?

**Comment by friso** [comment]
It is possible to change the `divolte.js` filename as documented [here](http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/userdoc/html/configuration.html#browser-source-property-javascript-name), so you could give that a try. Additionally, it might help to change the default event callback URL, using [this](http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/userdoc/html/configuration.html#browser-source-property-event-suffix). You can also change the names of the cookies that Divolte sets, which might help in some cases.

I don't know if it will solve the problem, but surely worth a shot.

**Comment by friso** [comment]
Keep in mind that changing the names of the cookies in a production environment will reset all party IDs.

**Comment by MrMoronIV** [comment]
I'm on a fresh install just figuring things out so everything is still fine.

I changed the filename and that didn't block it, however, the event trigger was blocked after that, will try to change the event callback url and investigate further.

**Comment by MrMoronIV** [comment]
I changed the filename with a nginx location redirect, but I can't get it to work using the normal config:

```
  // Sources, sinks and mappings are provided only if the user hasn't
  // specified anything. Due to the merging rules for configuration,
  // defaults are not present here: this is handled in code.
  sources {
    a_source {
      type = browser
      javascript.name = tracking.js
    }
  }
```
This isn't picked up, how do I define it?

**Comment by MrMoronIV** [comment]
This did the trick, thanks for the quick feedback!

```
  sources {
    a_source {
      type = browser
      javascript.name = tracking.js
      event_suffix = web-event
    }
  }
```
