### ISSUE TITLE
How to install via RPM?

### ISSUE THREAD

**Issue by MrMoronIV** [divolte/divolte-collector#320]
I'm a bit confused as what this means:

```
The distributions provided for Divolte Collector are:

A .tar.gz archive distribution containing the binaries and startup scripts.
A .zip archive distribution containing the binaries and startup scripts.
A RPM that can be installed onto Red Hat/CentOS systems. This includes startup and init scripts.
```
Where can I find this RPM package?

**Comment by friso** [comment]
It's linked from the website (divolte.io) under Downloads. Direct link for 0.9.0 is [here](http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/distributions/divolte-collector-0.9.0-2.el7.noarch.rpm).

**Comment by MrMoronIV** [comment]
When I install the package:
```
yum install -y http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.9.0/distributions/divolte-collector-0.9.0-2.el7.noarch.rpm
```
it installs fine but after
```
service divolte-collector start
```
It doesn't occupy any port, `journalctl -xe`:
```
pam_unix(runuser:session): session opened for user divolte by (uid=0)
runuser[29721]: pam_unix(runuser:session): session closed for user divolte
```

Status is `running (exited)`. So something seems to be wrong with the rpm package and I don't get any errors. I got divolte running using the tar, but I would like to have it as a service so I can monitor it more easily.

**Comment by friso** [comment]
Anything in /var/log/divolte* ?

**Comment by MrMoronIV** [comment]
JAVA_HOME is not

**Comment by MrMoronIV** [comment]
Ok, I've set
`JAVA_HOME=/usr/`
in `/etc/divolte/divolte-env.sh` and it now runs fine!

I know that using logs in var/log is common practice, but an error on the service level would make sense as well, I wouldn't have opened this ticket otherwise.
