### ISSUE TITLE
Kafka SASL_SSL

### ISSUE THREAD

**Issue by MrMoronIV** [divolte/divolte-collector#327]
I'm a bit confused as to how to connect to kafka using SASL_SSL, is there an example somewhere?

I need to define a truststore with its password and a login mechanism (SCRAM, username/password) but am not sure what settings to define in the kafka block.

**Comment by krisgeus** [comment]
Does this help? https://github.com/divolte/divolte-collector/pull/174

**Comment by MrMoronIV** [comment]
It did, a little, but just enough to get me going:

Here's the Kafka config that worked for me:
```
        bootstrap.servers = "kafka1.domain.ext:9094,kafka2.domain.ext:9094,kafka3.domain.ext:9094"
        acks = 1
        retries = 1
        #compression.type = lz4
        max.in.flight.requests.per.connection = 1
        client.id = divolte
		
        ssl.truststore.location = /etc/divolte/client.truststore.jks
        ssl.truststore.password = blablabla
        sasl.mechanism = SCRAM-SHA-256
        sasl.jaas.config = "org.apache.kafka.common.security.scram.ScramLoginModule required username = divolte password = blablabla2;"
        security.protocol = SASL_SSL
```
