### ISSUE TITLE
Kafka topics error

### ISSUE THREAD

**Issue by icychocolate98** [divolte/divolte-collector#421]
Good morning,

I'm trying to send 2 custom events to kafka; the idea is send each event to its topic; but at the moment I receive both events in both topics.

I have configured 2 mappings with different schemas and 2 sinks (one for each mapping). What I exactly need is to map my custom events to a specific kafka topic.

I don't know what is exactly happening, do you hace any idea?

Thanks !
Manu

**Comment by josephwibowo** [comment]
I'm having this same exact issue. Sad that this repo isn't being maintained :(

My workaround for this is to use Kafka Connect to filter...
