### ISSUE TITLE
Describe in the doc that JAVA_HOME should be set

### ISSUE THREAD

**Issue by bbrumi** [divolte/divolte-collector#68]
~/Projects/divolte/divolte-collector-0.2-SNAPSHOT
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
~/Projects/divolte/divolte-collector-0.2-SNAPSHOT
$ which java
/usr/bin/java
~/Projects/divolte/divolte-collector-0.2-SNAPSHOT
$ ./bin/divolte-collector 
+======================================================================+
|      Error: JAVA_HOME is not set and Java could not be found         |
+----------------------------------------------------------------------+
| Please download the latest Oracle JDK from the Java web site         |
|       > http://www.oracle.com/technetwork/java/index.html <          |
|                                                                      |
| Divolte Collector requires Java 1.8 or later.                        |
| NOTE: This script will try to find Oracle Java 8 if you install      |
|       using the the RPM based installer.                             |
+======================================================================+

Op MAC heb ik de volgende in .bash_profile toegevoegd: 
export JAVA_HOME=$(/usr/libexec/java_home)

**Comment by asnare** [comment]
So it looks like @friso documented `JAVA_HOME` in d49dc58294bffa1d46ca58b7c33eecdc4d046ecc.

(In 5de584234c0ad3ce1da9e4120dc140d8549f8dc3 I also ensured it appears in the documentation index.)
