### ISSUE TITLE
Improvements on Getting started guide

### ISSUE THREAD

**Issue by abij** [divolte/divolte-collector#69]
The code-block for creating your own HTML contains an invalid link to divolte.js. Should be prefixed with http or something.

Following the guide I created my custom event in mapping.groovy, but the guide does not provide the information for the avro-schema. So the exception occurs:

    Exception in thread "main" io.divolte.server.recordmapping.SchemaMappingException: Field eventTypeField does not exist in Avro schema; error in mapping eventType() onto eventTypeField

You could provide the schema for quick copy paste in MyEventRecord:

    {
      "namespace": "io.divolte.examples.record",
      "type": "record",
      "name": "MyEventRecord",
      "fields": [
     ...
        { "name": "eventTypeField",          "type": "string"},
        { "name": "paramField",              "type": "string"},
        { "name": "otherParamField",         "type": "string"},
        { "name": "intField",                "type": "int"}
      ]
    }

**Comment by asnare** [comment]
So… going through the list:

1. The example HTML that we use in documentation uses a script source that intentionally omits the `http`/`https` scheme. This is a common convention for HTML where you don't know if it's being accessed over HTTP or HTTPS. It's technically a relative URL, and browsers work fine with this.

2. The _Getting Started_ guide does describe creating an Avro schema and mapping to it in the _Bring your own schema_ section.

3. Yes, you generally should provide default values for fields.

4. I'm not sure where the outer mapping `{}` was missing; the groovy file doesn't need this. (All the examples currently work with cut'n'paste, so we probably fixed this in the meantime.)
