### ISSUE TITLE
Warning that HDFS dirs should be created

### ISSUE THREAD

**Issue by bbrumi** [divolte/divolte-collector#71]
Or something similar to: "HDFS directories are not automatically created"

**Comment by bbrumi** [comment]
Also specify who should own / which permission should de HDFS dirs have

**Comment by asnare** [comment]
It looks like @friso added some documentation mentioning to the _Getting Started_ guide in commit f4a885788e4e89f66e6a3dba5a76b9e9f1d8850d.

I've also just updated (44bc4dabd4efe5d0b7426e6dea6802447efe17ea) the documentation for HDFS sink properties to mention this.
