### ISSUE TITLE
Allow disabling of the automatic pageView event in configuration.

### ISSUE THREAD

**Issue by BHMath** [divolte/divolte-collector#92]
I notice in Piwik that it was possible to set a parameter like userId on every page without firing any event.

Is it possible to add something like this to divolte.

I manage to do a workaround for now but divolte stores both the pageView event and my customEvent.

Here my workaround : 
```javascript
<script src="//localhost:8290/divolte.js" async defer onload="fireDivolteEvent();"></script>
<script type="text/javascript">
function fireDivolteEvent(eventName, params) {
	// Set a default eventName if none provided
	eventName = (!eventName) ? 'displayPage' : eventName;
	// Create a default param oject to set the userId
	params = (!params) ? {} : params;
	// Define the user id if it's not done already
	params.userId = (!params.userId) ? getUserIdFromMyApp() : params.userId;
	// Add all page defined params if exists
	if (typeof divolteParams !== 'undefined') {
		$.extend(params, divolteParams);
	}
	//Fire the event in Divolte
	divolte.signal(eventName, params);
}
</script>
```

I suggest to modify lines 949 and 955 of divolte.js to `signal('pageView', divolteParams);`

And then in my webapp i could do this
```javascript
<script type="text/javascript">var divolteParams = { p1: 'v1',  p2: 'v2'};</script>
<script src="//localhost:8290/divolte.js" async defer"></script>
```
According to this, i can always pass user defined parameter on my own like my own userId or whatever I need to track.

Obviously some check must be done before applying this parameters.

**Comment by friso** [comment]
We should look into this a bit. Another option that we're currently thinking about is to make a server side configuration for disabling the automatic default pageView event altogether, giving the client side full control over the first / only event that is sent. Would that solve your problem as well?

**Comment by BHMath** [comment]
Yes this would solve y problem, i would use my onLoad event and only get my custom event with my own parameters. 

Currently i get one 'pageView' event with all information set to null or "" or 0. So my storage would be cleaner if I can remove this default event.

But I think allowing people to add custom defined parameters to the default event is the better. No need to add my own function in js. I would only have to define my parameters on a page.

**Comment by friso** [comment]
True, though I think not everybody might appreciate setting up globally scoped variables with fixed names on their pages. There are other ways to pass variables to the script (e.g. using the # part of the script url), but these are harder to support across browsers and in older browsers.

For now, we'll implement disabling the default event. The default config will keep it enabled, because we'd like the minimal deployment of just dropping the script tag into a page to do something useful.

**Comment by BHMath** [comment]
I understand. Disabling the default event is ok for me at the moment.

**Comment by friso** [comment]
OK. We'll fix that.

In the mean time as an immediate work around, if you can set a cookie with the user ID (with the correct cookie domain, so the collector receives the cookie in the requests), you can use that in the mapping, using something like:

`map cookie('user_id') onto 'userId'`

You could set the cookie from JS, so without onload, but just set it before you load the divolte.js.

**Comment by friso** [comment]
This is now merged. You can expect a nightly build with this functionality shortly. Otherwise expect a 0.3 release probably next week.
