### ISSUE TITLE
Custom even parameters should not be encoded but passed as is.

### ISSUE THREAD

**Issue by friso** [divolte/divolte-collector#93]
Currently custom even parameters are base36 encoded in case of numbers and encoded as t/f for booleans. These values are not useful when mapping, as the mapping exposes no functionality for decoding these back into something that parses into the respective primitives again. Pending #91 they should be sent as is, rather than encoded.

This will likely be fixed as part of the fix for #92.

**Comment by asnare** [comment]
This was fixed in 68eb1238599bca3532ff9d066145962fcef3ca85, which was merged as part of pull request #94.
