### ISSUE TITLE
Divolte.javascript documentation error

### ISSUE THREAD

**Issue by BHMath** [divolte/divolte-collector#97]
Hi,

I think there is an error in the documentation. I tried to follow it to disable the default pageView event but the documentation tells me I need this line :

divolte.tracking.javascript.auto_page_view_event
Description:	

When false, the served JavaScript will not automatically send a pageView event after being loaded. This way clients can send a initial event themselves and have full control over the event type and the custom parameters that are sent with the initial event.
Default:	

true
Example:	
```
divolte.tracking.javascript {
  auto_page_view_event = false
}
```
But for it to get functionnal I needed to set this 
```
divolte.javascript {
  auto_page_view_event = false
}
```

Can you update documentation please. I don't know if all javascript configuration is the same but I'm pretty sure it is.

**Comment by friso** [comment]
Even worse: all of the javascript related config options are wrongly documented as being in the divolte.tracking namespace. Fix coming up...
